compatibility_date = "2024-11-11"
workers_dev = false
logpush = true

[env.production]
name = "engine"
route = { pattern = "engine.travelese.ai/*", zone_name = "travelese.ai" }

kv_namespaces = [
  { binding = "KV", id = "b321b928d84747a4b899b21894a720c2" },
  { binding = "ENRICH_KV", id = "1ce9f0355d854a569f72bfccbfbea369"}
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "" },
]

[env.production.ai]
binding = "AI"
provider = "llama"
model = "llama-3.3"
jurisdiction = "eu"

[env.staging]
name = "engine-staging"
route = { pattern = "engine-staging.travelese.ai/*", zone_name = "travelese.ai" }

kv_namespaces = [
  { binding = "KV", id = "b321b928d84747a4b899b21894a720c2" },
  { binding = "ENRICH_KV", id = "72051e71ec964899a3d0da95df04b92f" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "" },
]

[env.staging.ai]
binding = "AI"
provider = "llama"
model = "llama-3.3"
jurisdiction = "eu"

[env.development]
name = "engine-dev"

[observability]
enabled = true
